# Site settings
title: Georg Zänker
email: georg.zanker14@imperial.ac.uk
url: https://gaedz.github.io
description: "Vote Georg for Webmaster 2015!"

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 80B3FF
  secondary: 444444
  secondary-dark: 666666

# Footer settings
footer:
  copyright: Georg Zänker
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/GeorgZaenker
  - title: facebook
    url: https://www.facebook.com/georgdocsocwebmaster
  - title: github
    url: https://github.com/GaedZ

# Postal address (add as many lines as necessary)
address:
  - line: Computing Labs
  - line: 219 Huxley
  - line: Imperial College

# Credits content
credits: 'No Credits'

# Build settings
markdown: kramdown
permalink: pretty
