# Site settings
title: Georg Z채nker
email: contact@georgzaenker.de
url: https://gaedz.github.io
description: "Personal Website of Georg Z채nker"

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: ccffff #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Georg Z채nker
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/GeorgZaenker
  - title: facebook
    url: https://www.facebook.com/Rekneaz
  - title: stack-overflow
    url: http://stackoverflow.com/users/2782850/georg-z채nker
  - title: github
    url: https://github.com/GaedZ

# Postal address (add as many lines as necessary)
address:
  - line: Matthieustr. 9
  - line: 13127 Berlin
  - line: Germany

# Credits content
credits: 'No Credits'

# Build settings
markdown: kramdown
permalink: pretty
